version: '3.9'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - "5433:5433"
    depends_on:
       db:
         condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:16
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    secrets:
     - db-password
    volumes:
     - db-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=stat-collector
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
     - 5432
    healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

