# Generated by Django 5.0.3 on 2024-03-28 21:56

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": [
                    "-is_active",
                    django.db.models.functions.text.Lower("name"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="copy",
            options={"ordering": ["text"], "verbose_name_plural": "copies"},
        ),
        migrations.AlterModelOptions(
            name="placementtype",
            options={
                "ordering": [
                    "-is_active",
                    django.db.models.functions.text.Lower("name"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="statcollector",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
        migrations.AlterModelOptions(
            name="statistic",
            options={
                "ordering": [
                    "-is_active",
                    django.db.models.functions.text.Lower("name"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": [
                    "-is_active",
                    django.db.models.functions.text.Lower("name"),
                ]
            },
        ),
        migrations.AddField(
            model_name="statcollector",
            name="external_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="statcollector",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Biweekly"),
                    ("monthly", "Monthly"),
                ],
                default="daily",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statcollector",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="copy",
            name="placement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="creator.placement",
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="collector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="placements",
                to="creator.statcollector",
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="statistics",
            field=models.ManyToManyField(
                limit_choices_to={"is_active": True}, to="creator.statistic"
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="suppliers",
            field=models.ManyToManyField(
                limit_choices_to={"is_active": True}, to="creator.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="type",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="creator.placementtype",
            ),
        ),
        migrations.AlterField(
            model_name="statcollector",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collectors",
                to="creator.client",
            ),
        ),
    ]
