# Generated by Django 5.0.3 on 2024-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0003_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="period",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="period",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
