# Generated by Django 5.0.3 on 2024-04-10 19:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creator", "0004_alter_period_options_alter_period_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="statcollector",
            name="statcollector_unique_name_insensitive",
        ),
        migrations.AddConstraint(
            model_name="statcollector",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="statcollector_unique_name_insensitive",
                violation_error_message="Statistics Collector's name must be unique (case-insensitive)",
            ),
        ),
    ]
